-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/AutoModerator/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE automoderator_rev_score (
  amrs_id BIGSERIAL NOT NULL,
  amrs_timestamp TIMESTAMPTZ NOT NULL,
  amrs_rev INT NOT NULL,
  amrs_model SMALLINT NOT NULL,
  amrs_bucket SMALLINT NOT NULL,
  amrs_prob NUMERIC(3, 3) NOT NULL,
  amrs_pred SMALLINT NOT NULL,
  amrs_status SMALLINT NOT NULL,
  PRIMARY KEY(amrs_id)
);

CREATE INDEX amrs_rev_model_bucket ON automoderator_rev_score (
  amrs_rev, amrs_model, amrs_bucket
);

CREATE INDEX amrs_model_bucket_prob ON automoderator_rev_score (
  amrs_model, amrs_bucket, amrs_prob
);

CREATE UNIQUE INDEX amrs_id_rev_status ON automoderator_rev_score (amrs_id, amrs_rev, amrs_status);


CREATE TABLE automoderator_model (
  amm_id SMALLSERIAL NOT NULL,
  amm_name VARCHAR(32) NOT NULL,
  amm_version VARCHAR(32) NOT NULL,
  amm_is_current SMALLINT NOT NULL,
  PRIMARY KEY(amm_id)
);

CREATE INDEX amrm_model_status ON automoderator_model (amm_name, amm_is_current);

CREATE UNIQUE INDEX amrm_version ON automoderator_model (amm_name, amm_version);
