-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/AutoModerator/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/automoderator_rev_score (
  amrs_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  amrs_timestamp BLOB NOT NULL,
  amrs_rev INTEGER UNSIGNED NOT NULL,
  amrs_model SMALLINT NOT NULL,
  amrs_bucket SMALLINT NOT NULL,
  amrs_prob NUMERIC(3, 3) NOT NULL,
  amrs_pred SMALLINT NOT NULL,
  amrs_status SMALLINT NOT NULL
);

CREATE INDEX amrs_rev_model_bucket ON /*_*/automoderator_rev_score (
  amrs_rev, amrs_model, amrs_bucket
);

CREATE INDEX amrs_model_bucket_prob ON /*_*/automoderator_rev_score (
  amrs_model, amrs_bucket, amrs_prob
);

CREATE UNIQUE INDEX amrs_id_rev_status ON /*_*/automoderator_rev_score (amrs_id, amrs_rev, amrs_status);


CREATE TABLE /*_*/automoderator_model (
  amm_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  amm_name VARCHAR(32) NOT NULL,
  amm_version VARCHAR(32) NOT NULL,
  amm_is_current SMALLINT NOT NULL
);

CREATE INDEX amrm_model_status ON /*_*/automoderator_model (amm_name, amm_is_current);

CREATE UNIQUE INDEX amrm_version ON /*_*/automoderator_model (amm_name, amm_version);
